# -*- coding: utf-8 -*-
"""Limpiar transacciones.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XVcIImCWcj9WHSQYTwYPY85bJz9dMvix

El presente archivo tiene como objetivo, poder manipuar los datos de las transacciones para poder limpiar el archivo. El archivo contiene muchas columnas que no son funcionales en el análisis de datos, asi como columnas con tipo de dato incorrecto, etc.
"""

#Importar librerías que se usaran en la limpieza
import pandas as pd
import os
import zipfile

#Revisar en que carpeta estan cargados los archivos para poder leerlo
os.getcwd()

# Se lee y guarda la infromación en la variable en un dataframe abreviado "df"
df = pd.read_excel("/content/BD_TRANSACCIONES_PRUEBA.xlsx")

#Se convierte el archivo de xlsx a formato csv
df.to_csv('archivo.csv', index=False)

#Se revisa el tipo de dato de cada columna
df.info()

#Muestra Totas las columnas de la tabla
df.columns

#Muestra de 5 datos de la tabla completa para ver como se visualiza el dato
df.head(5)

#modifica la columna de fecha de aplicación para que se reconozca como una columna de fecha
df['FECHA DE APLICACION']= pd.to_datetime(df['FECHA DE APLICACION'], errors="raise")

#Se eligen las columnas que van a quedarse en el df
columnas_seleccionadas = ['ID','TIPO DE TX','MERCHANT','USER ID','TIPO BIN',' IMPORTE ','FECHA DE APLICACION','NOMBRE TARJETAHABIENTE','BANCO EMISOR', 'MARCA', 'APROBADA','LONGITUD', 'LATITUD','IMPORTE NETO','OPERATIVA','MES','AÑO']

#el nuevo df, se le atribuye a la variable "df"
df = df[columnas_seleccionadas]

#Muestra el # de columnas y filas del DF

df.shape

#Revisas como queda la info
df.head(5)

#como renombrar un encabezado o columna
#df_columnas_selecionadas.rename(columns = {"TESORERIA TPV": "TIPO DE OPERATIVA"}, inplace=True)

#df_columnas_selecionadas.groupby('USER ID').agg({'IMPORTE':'sum'}).sort_values('IMPORTE',ascending=False).head(10)

#Se descarga el archivo en formato csv para poder leerlo en power bi
df.to_csv("Transacciones_limpias.csv")